-- ledgerlens schema. Hand-written, applied on every startup (spring.sql.init.mode=always),
-- so every statement must stay idempotent. Money is NUMERIC(14,2) everywhere.
-- The plpgsql function body uses old-style quoted syntax because Spring's script
-- runner splits statements on ';' and does not understand $$ dollar-quoting.

CREATE TABLE IF NOT EXISTS ingest_batches (
    id         UUID PRIMARY KEY,
    source     VARCHAR(20) NOT NULL CHECK (source IN ('CSV', 'RAZORPAY')),
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id UUID NOT NULL REFERENCES ingest_batches(id),
    order_id VARCHAR(40) NOT NULL,
    order_ts TIMESTAMP NOT NULL,
    amount   NUMERIC(14,2) NOT NULL,
    CONSTRAINT uq_orders_batch_order UNIQUE (batch_id, order_id)
);

CREATE TABLE IF NOT EXISTS payments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id   UUID NOT NULL REFERENCES ingest_batches(id),
    payment_id VARCHAR(40) NOT NULL,
    order_id   VARCHAR(40) NOT NULL,
    method     VARCHAR(20) NOT NULL CHECK (method IN ('UPI', 'CARD', 'NETBANKING', 'WALLET')),
    amount     NUMERIC(14,2) NOT NULL,
    fee        NUMERIC(14,2) NOT NULL,
    gst        NUMERIC(14,2) NOT NULL,
    net_amount NUMERIC(14,2) NOT NULL,
    status     VARCHAR(20) NOT NULL CHECK (status IN ('CAPTURED', 'FAILED')),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_payments_batch_payment UNIQUE (batch_id, payment_id)
);

CREATE TABLE IF NOT EXISTS refunds (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id   UUID NOT NULL REFERENCES ingest_batches(id),
    refund_id  VARCHAR(40) NOT NULL,
    payment_id VARCHAR(40) NOT NULL,
    order_id   VARCHAR(40),
    amount     NUMERIC(14,2) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_refunds_batch_refund UNIQUE (batch_id, refund_id)
);

CREATE TABLE IF NOT EXISTS disputes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id    UUID NOT NULL REFERENCES ingest_batches(id),
    dispute_id  VARCHAR(40) NOT NULL,
    payment_id  VARCHAR(40) NOT NULL,
    opened_at   TIMESTAMP NOT NULL,
    status      VARCHAR(20) NOT NULL CHECK (status IN ('OPEN', 'WON', 'LOST')),
    resolved_at TIMESTAMP,
    CONSTRAINT uq_disputes_batch_dispute UNIQUE (batch_id, dispute_id)
);

CREATE TABLE IF NOT EXISTS settlement_batches (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id   UUID NOT NULL REFERENCES ingest_batches(id),
    utr        VARCHAR(30) NOT NULL,
    settled_on DATE NOT NULL,
    amount     NUMERIC(14,2) NOT NULL,
    CONSTRAINT uq_settlement_batches_batch_utr UNIQUE (batch_id, utr)
);

CREATE TABLE IF NOT EXISTS settlement_lines (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id                UUID NOT NULL REFERENCES ingest_batches(id),
    settlement_batch_row_id BIGINT NOT NULL REFERENCES settlement_batches(id),
    line_type               VARCHAR(10) NOT NULL CHECK (line_type IN ('PAYMENT', 'REFUND')),
    entity_id               VARCHAR(40) NOT NULL,
    order_id                VARCHAR(40),
    amount                  NUMERIC(14,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS bank_entries (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id    UUID NOT NULL REFERENCES ingest_batches(id),
    entry_date  DATE NOT NULL,
    description VARCHAR(200),
    utr         VARCHAR(30),
    amount      NUMERIC(14,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS matches (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id                UUID NOT NULL REFERENCES ingest_batches(id),
    match_type              VARCHAR(40) NOT NULL,
    order_row_id            BIGINT REFERENCES orders(id),
    settlement_line_row_id  BIGINT REFERENCES settlement_lines(id),
    settlement_batch_row_id BIGINT REFERENCES settlement_batches(id),
    bank_entry_row_id       BIGINT REFERENCES bank_entries(id),
    amount                  NUMERIC(14,2) NOT NULL,
    created_at              TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS exceptions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id       UUID NOT NULL REFERENCES ingest_batches(id),
    status         VARCHAR(30) NOT NULL CHECK (status IN ('MATCHED', 'PAYMENT_FAILED', 'HELD_DISPUTE',
                       'REFUND_PRIOR_CYCLE', 'BANK_DUPLICATE', 'BANK_MISSING', 'AMOUNT_MISMATCH', 'UNKNOWN')),
    entity_ref     VARCHAR(40) NOT NULL,
    reason         VARCHAR(500) NOT NULL,
    confidence     NUMERIC(4,3) NOT NULL,
    origin         VARCHAR(10) NOT NULL CHECK (origin IN ('RULE', 'LLM')),
    source_row_ids JSONB,
    created_at     TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_log (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logged_at TIMESTAMP NOT NULL DEFAULT now(),
    batch_id  UUID,
    action    VARCHAR(50) NOT NULL,
    detail    TEXT
);


CREATE TABLE IF NOT EXISTS batch_health (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id    UUID NOT NULL REFERENCES ingest_batches(id),
    metrics     JSONB NOT NULL,
    computed_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_batch_health_batch UNIQUE (batch_id)
);

CREATE TABLE IF NOT EXISTS anomaly_alerts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id       UUID NOT NULL REFERENCES ingest_batches(id),
    metric         VARCHAR(60) NOT NULL,
    current_value  NUMERIC(14,6) NOT NULL,
    baseline_value NUMERIC(14,6) NOT NULL,
    ratio          NUMERIC(14,6) NOT NULL,
    severity       VARCHAR(10) NOT NULL CHECK (severity IN ('WARN', 'HIGH')),
    source_row_ids JSONB,
    likely_cause   VARCHAR(500),
    suggested_check VARCHAR(300),
    confidence     NUMERIC(4,3),
    created_at     TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_orders_batch ON orders (batch_id);
CREATE INDEX IF NOT EXISTS idx_payments_batch_order ON payments (batch_id, order_id);
CREATE INDEX IF NOT EXISTS idx_refunds_batch ON refunds (batch_id);
CREATE INDEX IF NOT EXISTS idx_settlement_lines_batch_order ON settlement_lines (batch_id, order_id);
CREATE INDEX IF NOT EXISTS idx_bank_entries_batch_utr ON bank_entries (batch_id, utr);
CREATE INDEX IF NOT EXISTS idx_matches_batch ON matches (batch_id);
CREATE INDEX IF NOT EXISTS idx_exceptions_batch ON exceptions (batch_id);
CREATE INDEX IF NOT EXISTS idx_batch_health_batch ON batch_health (batch_id);
CREATE INDEX IF NOT EXISTS idx_anomaly_alerts_batch ON anomaly_alerts (batch_id);

CREATE OR REPLACE FUNCTION audit_log_block_mutation() RETURNS trigger AS
'BEGIN
    RAISE EXCEPTION ''audit_log is append-only: % blocked'', TG_OP;
END;'
LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_audit_log_append_only
    BEFORE UPDATE OR DELETE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION audit_log_block_mutation();

-- Hybrid Ask retrieval. Kept out of the reconciliation path entirely: nothing above reads this
-- table, and a batch reconciles identically whether or not it was ever indexed.
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS rag_documents (
    id          UUID PRIMARY KEY,
    batch_id    UUID NOT NULL REFERENCES ingest_batches (id) ON DELETE CASCADE,
    record_id   VARCHAR(120) NOT NULL,
    record_type VARCHAR(40) NOT NULL,
    content     TEXT NOT NULL,
    embedding   vector,
    metadata    JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMP NOT NULL DEFAULT now()
);

-- Every search is filtered by batch, so that is the index that matters.
CREATE INDEX IF NOT EXISTS idx_rag_documents_batch ON rag_documents (batch_id);
